package slippymap

import (
	"testing"
)

/*
	Test data generated by inspecting the OSM maps as below

	https://www.openstreetmap.org/#map=19/51.32842/-0.22345
	==> https://tile.openstreetmap.org/19/261818/174757.png
	==> https://tile.openstreetmap.org/18/130909/87378.png
	==> https://tile.openstreetmap.org/17/65454/43689.png

	https://www.openstreetmap.org/#map=19/-0.60306/-90.67253
	==> https://tile.openstreetmap.org/19/130092/263022.png
	==> https://tile.openstreetmap.org/18/65046/131511.png
	==> https://tile.openstreetmap.org/17/32523/65755.png

	https://www.openstreetmap.org/#map=19/-43.84808/147.02493
	==> https://tile.openstreetmap.org/19/476264/333339.png
	==> https://tile.openstreetmap.org/18/238132/166669.png
	==> https://tile.openstreetmap.org/17/119066/83334.png
*/

func TestAgainstOSM(t *testing.T) {
	tests := []struct {
		lat float64
		lng float64
		z   int
		x   int
		y   int
	}{
		{51.32842, -0.22345, 19, 261818, 174757},
		{51.32842, -0.22345, 18, 130909, 87378},
		{51.32842, -0.22345, 17, 65454, 43689},
		{-0.60306, -90.67253, 19, 130092, 263022},
		{-0.60306, -90.67253, 18, 65046, 131511},
		{-0.60306, -90.67253, 17, 32523, 65755},
		{-43.84808, 147.02493, 19, 476264, 333339},
		{-43.84808, 147.02493, 18, 238132, 166669},
		{-43.84808, 147.02493, 17, 119066, 83334},
	}

	for _, test := range tests {
		x, y, err := LatLng2TileZoomXY(test.lat, test.lng, test.z)
		if err != nil {
			t.Fatal(err)
		}
		if test.x != x || test.y != y {
			t.Errorf("For %f, %f at zoom %d expected %d, %d got %d, %d\n", test.lat, test.lng, test.z, test.x, test.y, x, y)
		}
	}
}
